apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-backend-config
data:
  DB_HOST: "production-mysql-db.csxqa04mi0fl.us-east-1.rds.amazonaws.com"      #"34.27.23.176"
  DB_PORT: "3306"
  DB_NAME: "online_banking_system"