apiVersion: v1
kind: Secret
metadata:
  name: bank-backend-secret
type: Opaque
data:
  DB_USERNAME: YWRtaW4=                               # cm9vdA==
  DB_PASSWORD: QmFua0FwcDIwMjVTZWN1cmVQYXNzIQ==             # c3VwcG9ydEAxMjNBQkM=


## echo -n "root" | base64
## echo -n "password123ABC" | base64
